---
title: "README"
author: "Zachary McCaw"
date: "`r Sys.Date()`"
output: 
  html_document: 
    keep_md: TRUE
--- 

```{r global_options, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  warning = FALSE, 
  message = FALSE, 
  cache = TRUE
)
library(MGMM)
```

## Survival Bands
This package generates simultaneous confidence bands for a single survival curve, and for the difference of two survival curves, using the method of [Prazen et al (1997)](https://onlinelibrary.wiley.com/doi/abs/10.1111/1467-9469.t01-1-00065). 

## Compact Example

```{r, fig.width = 6.5, fig.height = 3.0, fig.align = 'center'}
library(Bands)
library(Temporal)
set.seed(2014)
data0 <- rGamma(n = 1e2, a = 1, l = 1/2, p = 0.2)
data0$arm <- 0
data1 <- rGamma(n = 1e2, a = 1, l = 1/4, p = 0.2)
data1$arm <- 1
data <- rbind(data0, data1)
ep_band <- SurvBands(
  time = data$time,
  status = data$status,
  arm = data$arm
)
show(ep_band)
plot(ep_band)
```

## Vignette

The vignette may be found [here](https://github.com/zrmacc/Bands/blob/master/vignettes/Vignette.pdf).
